// Generated by `python -m app.seed_demo` as demo-site/config.js (gitignored: contains publishable keys).
window.MSB_DEMO = {
  web: "http://localhost:3000",
  customer: { app: "<assistant id>", key: "<publishable key>" },
  staff: { app: "<assistant id>", key: "<publishable key>" },
};
