#!/usr/bin/env bash
# Runs ON THE SERVER. Uploaded and invoked by deploy/deploy.sh — you normally never call it by hand.
#
#   remote.sh init-env <public-domain>   create ~/querion/shared/.env once (reads SEED_* lines on stdin)
#   remote.sh deploy                     install/refresh the stack from ~/querion/incoming.tar.gz
#
# Data-safety contract (every deploy after the first):
#   * code in ~/querion/app is replaced; data lives only in Docker volumes that are never removed
#   * ~/querion/shared/.env is created once and never overwritten
#   * the demo seed runs exactly once (marker file AND an empty `apps` table are both required)
#   * the only data change is `alembic upgrade head`, preceded by a pg_dump backup
set -Eeuo pipefail

ROOT="$HOME/querion"
APP="$ROOT/app"
SHARED="$ROOT/shared"
ARCHIVE="$ROOT/incoming.tar.gz"
BACKUP_KEEP=10

log()  { printf '\n\033[1;34m==> %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m!!  %s\033[0m\n' "$*"; }
die()  { printf '\033[1;31mxx  %s\033[0m\n' "$*" >&2; exit 1; }

dc() { sudo docker compose -f "$APP/deploy/docker-compose.prod.yml" --project-directory "$APP/deploy" "$@"; }

# ---------------------------------------------------------------------------
ensure_docker() {
  if command -v docker >/dev/null 2>&1 && sudo docker compose version >/dev/null 2>&1; then
    return
  fi
  log "Cài Docker Engine + compose plugin (lần đầu)"
  curl -fsSL https://get.docker.com | sudo sh
  sudo systemctl enable --now docker
  sudo docker compose version
}

# ---------------------------------------------------------------------------
init_env() {
  local domain="${1:?public domain required}"
  mkdir -p "$SHARED/demo-site" "$SHARED/backups"
  if [[ -f "$SHARED/.env" ]]; then
    cat >/dev/null   # drain stdin; the existing .env is never touched
    log ".env đã tồn tại — giữ nguyên"
    return
  fi
  log "Tạo $SHARED/.env (secret ngẫu nhiên, chỉ lần đầu)"
  local seed_lines
  # only accept SEED_*=value lines from stdin, nothing else
  seed_lines="$(grep -E '^SEED_(LLM|EMBEDDING)_(PROVIDER|MODEL|BASE_URL|API_KEY)=[^[:space:]]+$' || true)"
  grep -q '^SEED_LLM_API_KEY=' <<<"$seed_lines" || warn "Không có SEED_LLM_API_KEY: trợ lý sẽ báo chưa cấu hình LLM"
  grep -q '^SEED_EMBEDDING_API_KEY=' <<<"$seed_lines" || warn "Không có SEED_EMBEDDING_API_KEY: văn bản sẽ không lập chỉ mục được"

  local fernet
  fernet="$(python3 -c 'import base64,os;print(base64.urlsafe_b64encode(os.urandom(32)).decode())')"
  umask 077
  cat >"$SHARED/.env" <<EOF
# Generated by deploy/remote.sh on $(date -Iseconds). Never overwritten by later deploys.
PUBLIC_DOMAIN=$domain
BRAND_NAME=MSB Knowledge Assistant

POSTGRES_USER=querion
POSTGRES_PASSWORD=$(openssl rand -hex 24)
POSTGRES_DB=querion
MINIO_ROOT_USER=querion
MINIO_ROOT_PASSWORD=$(openssl rand -hex 24)

JWT_SECRET=$(openssl rand -hex 32)
ENCRYPTION_KEY=$fernet
SUPER_ADMIN_EMAIL=admin@querion.io
SUPER_ADMIN_PASSWORD=$(openssl rand -hex 9)

PII_ENGINE=presidio
ENABLE_MCP_STDIO=false

$seed_lines
EOF
  chmod 600 "$SHARED/.env"
  log ".env đã tạo (chmod 600)"
}

# ---------------------------------------------------------------------------
psql_q() { dc exec -T postgres sh -c 'psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -At -c "$1"' _ "$1"; }

wait_healthy() {
  local svc="$1" tries="${2:-60}"
  for _ in $(seq 1 "$tries"); do
    local cid state
    cid="$(dc ps -q "$svc" 2>/dev/null || true)"
    state="$( [[ -n "$cid" ]] && sudo docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "$cid" 2>/dev/null || echo missing)"
    [[ "$state" == "healthy" ]] && return 0
    sleep 3
  done
  dc logs --tail 60 "$svc" || true
  die "$svc không healthy"
}

backup_db() {
  local has_schema
  has_schema="$(psql_q "select to_regclass('public.alembic_version') is not null" || echo f)"
  [[ "$has_schema" == "t" ]] || { log "Database mới, không cần backup"; return; }
  local file="$SHARED/backups/pre-migrate-$(date +%Y%m%d-%H%M%S).dump"
  log "Backup database trước migration → $file"
  dc exec -T postgres sh -c 'pg_dump -U "$POSTGRES_USER" -d "$POSTGRES_DB" -Fc' >"$file"
  [[ -s "$file" ]] || die "backup rỗng, dừng deploy để bảo vệ dữ liệu"
  ls -1t "$SHARED"/backups/pre-migrate-*.dump 2>/dev/null | tail -n +$((BACKUP_KEEP + 1)) | xargs -r rm -f
}

seed_ops() {
  # Trợ lý Vận hành: chạy MỌI lần deploy, khác với seed demo chỉ chạy một lần.
  #
  # Không vi phạm quy tắc "deploy không đụng dữ liệu": lệnh này chỉ quản lý đúng những thứ nó
  # sở hữu — đơn vị Hệ thống, kho Cẩm nang vận hành, trợ lý hệ thống — và chỉ tạo cái còn thiếu.
  # Nó không bao giờ đè lên system prompt, model hay danh sách gợi ý mà super admin đã sửa.
  # Riêng văn bản cẩm nang thì đồng bộ theo mã nguồn, vì cẩm nang là tài liệu của sản phẩm và
  # bản trong repo mới là bản đúng.
  log "Đồng bộ Trợ lý Vận hành và cẩm nang"
  dc exec -T api python -m app.seed_ops 2>&1 \
    | grep -vE 'sqlalchemy|^(FROM|WHERE|SELECT|INSERT|UPDATE)' || warn "seed_ops thất bại (bong bóng vận hành có thể chưa sẵn sàng)"

  # Kỹ năng nghiệp vụ mẫu. Tách khỏi seed_demo vì seed_demo chỉ chạy một lần theo marker, nên
  # kỹ năng thêm sau sẽ không bao giờ tới được bản deploy đã seed từ trước.
  log "Đồng bộ kỹ năng nghiệp vụ mẫu"
  dc exec -T api python -m app.seed_skills 2>&1 \
    | grep -vE 'sqlalchemy|^(FROM|WHERE|SELECT|INSERT|UPDATE)' || warn "seed_skills thất bại"
}

reset_demo() {
  # Xoá sạch dữ liệu nghiệp vụ (trừ khoá AI) rồi seed lại bộ demo chuẩn. Luôn pg_dump trước.
  # Chỉ chạy khi được yêu cầu tường minh bằng `remote.sh reset-demo` — deploy không bao giờ gọi.
  backup_db
  log "Reset dữ liệu demo (xoá + seed lại)"
  dc exec -T api python -m app.reset_demo --yes 2>&1 \
    | grep -vE 'sqlalchemy|^(FROM|WHERE|SELECT|INSERT|UPDATE)' || die "reset_demo thất bại"
  touch "$SHARED/.seeded"
  wait_indexing 180
}

wait_indexing() {
  local tries="${1:-120}" pending
  log "Chờ worker lập chỉ mục văn bản"
  for _ in $(seq 1 "$tries"); do
    pending="$(psql_q "select count(*) from documents where status in ('uploaded','indexing')" || echo '?')"
    [[ "$pending" == "0" ]] && break
    printf '   còn %s văn bản đang lập chỉ mục\n' "$pending"
    sleep 5
  done
  psql_q "select status, count(*) from documents group by status" | sed 's/^/   /'
}

seed_once() {
  local apps
  apps="$(psql_q 'select count(*) from apps' || echo error)"
  if [[ -f "$SHARED/.seeded" ]]; then
    log "Đã seed trước đó (marker) — bỏ qua seed"
    return
  fi
  if [[ "$apps" != "0" ]]; then
    warn "Bảng apps đã có dữ liệu ($apps) — không seed, chỉ ghi marker"
    touch "$SHARED/.seeded"
    return
  fi
  log "Seed dữ liệu demo (lần đầu)"
  dc exec -T api python -m app.seed_demo 2>&1 | grep -vE 'sqlalchemy|^(FROM|WHERE|SELECT|INSERT|UPDATE)' || die "seed thất bại"
  touch "$SHARED/.seeded"
  wait_indexing
}

deploy() {
  [[ -f "$ARCHIVE" ]] || die "thiếu $ARCHIVE"
  [[ -f "$SHARED/.env" ]] || die "thiếu $SHARED/.env — chạy init-env trước"
  ensure_docker
  mkdir -p "$SHARED/demo-site" "$SHARED/backups"

  log "Giải nén code mới (dữ liệu và .env không bị động tới)"
  rm -rf "$APP.new"
  mkdir -p "$APP.new"
  tar -xzf "$ARCHIVE" -C "$APP.new"
  ln -sfn "$SHARED/.env" "$APP.new/deploy/.env"
  if [[ -d "$APP" ]]; then rm -rf "$APP.prev"; mv "$APP" "$APP.prev"; fi
  mv "$APP.new" "$APP"

  log "Build image (dịch vụ cũ vẫn chạy trong lúc build)"
  dc build

  log "Khởi động hạ tầng"
  dc up -d postgres redis minio minio-init
  wait_healthy postgres
  wait_healthy redis

  backup_db

  log "Migration: alembic upgrade head"
  dc run --rm --no-deps api alembic upgrade head
  # LangGraph's own checkpoint tables (outside Alembic). The API also does this at startup.
  dc run --rm --no-deps api python -c 'import asyncio; from app.services.agent_runtime import setup_checkpointer; asyncio.run(asyncio.wait_for(setup_checkpointer(), 120))' \
    || warn "checkpoint schema chưa cập nhật, API sẽ thử lại khi khởi động"

  log "Khởi động ứng dụng"
  dc up -d --remove-orphans
  # Caddy (demo-site, Caddyfile) and the tool mocks (demo-mock) bind-mount files of this release.
  # Compose leaves them running when their config is unchanged, still mounted on the previous
  # release directory — which the next deploy deletes (demo site then answers 404). Recreate them.
  dc up -d --no-deps --force-recreate caddy mock-core mock-mcp mock-dwh
  # jobs-worker and scheduler run the API image; recreate them so a deploy picks up new code
  dc up -d --no-deps --force-recreate jobs-worker scheduler
  wait_healthy api 80

  seed_once
  seed_ops

  log "Dọn image cũ không dùng (không đụng volume)"
  sudo docker image prune -f >/dev/null || true

  log "Trạng thái"
  dc ps --format 'table {{.Service}}\t{{.Status}}'
  local domain
  domain="$(grep -E '^PUBLIC_DOMAIN=' "$SHARED/.env" | cut -d= -f2-)"
  printf '\nWeb:        https://%s\nCán bộ:     https://%s/staff/login\nDemo nhúng: https://demo.%s\n' "$domain" "$domain" "$domain"
}

case "${1:-}" in
  init-env) shift; init_env "$@" ;;
  deploy)   deploy ;;
  reset-demo) reset_demo ;;
  *) die "usage: remote.sh init-env <domain> | deploy | reset-demo" ;;
esac
